- hosts: all
  become: yes
  gather_facts: True
  tasks:
       
    - name: install apt fail2ban packages on debian
      apt:
        name:
          - fail2ban
        state: installed
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


    - name: install apt fail2ban packages on centos
      yum:
        name: 
          - fail2ban
        state: installed
        update_cache: yes
        enablerepo: epel
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
          

    - name: copy config
      copy:
        src: jail.local.j2
        dest: /etc/fail2ban/jail.local
        force: no
        owner: root
        group: root
        mode: 0644
