- hosts: all
  sudo: yes
  gather_facts: True
  tasks:
    - debug: msg={{inventory_hostname}},{{ansible_fqdn}},{{ansible_distribution}},{{ansible_distribution_version}}
       
    - name: install apt fail2ban packages on debian
      apt:
        name: "{{ item }}"
        state: installed
        update_cache: yes
        cache_valid_time: 3600
      with_items:
        - fail2ban
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


    - name: install apt fail2ban packages on centos
      yum:
        name: "{{ item }}"
        state: installed
        update_cache: yes
      with_items:
        - fail2ban
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
          

    - name: copy config
      copy:
        src: jail.local.j2
        dest: /etc/fail2ban/jail.local
        force: no
        owner: root
        group: root
        mode: 0644
